import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { ReviewForm } from "../components/ReviewForm";
import { Message, useOpenAI } from "../hooks/useOpenAI";
import "tailwindcss/tailwind.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { response, loading, generateResponse } = useOpenAI();

  const handleGenerate = (messages: Message[]) => {
    generateResponse(messages);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {" "}
        <div className="container mx-auto my-10 px-4">
          <h1 className="text-3xl font-bold mb-6">お弁当レビュー補助ツール</h1>
          <ReviewForm onGenerate={handleGenerate} />
          {loading && <p className="text-xl">文章を生成中...</p>}
          {response && (
            <div className="mt-6">
              <h2 className="text-2xl font-bold mb-4">生成された文章:</h2>
              <p className="text-xl">{response}</p>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
